name        : iptables
version     : 0.9.8.0
release     : 3
source      :
    - http://www.netfilter.org/projects/iptables/files/iptables-1.4.18.tar.bz2 : 14a99fb8b0ca22027a9ac6eb72fa32c834ceb3073820e0ba79bf251c6a7bcf3c
license     :
    - LGPL-3.0
summary     : Netfilter firewall
description : |
    Netfilter firewall
setup      : |
    %configure  --exec-prefix=\
                --bindir=/usr/bin                      \
                --with-xtlibdir=/lib/xtables           \
                --enable-libipq                        \
                --enable-devel
build      : |
    %make
install    : |
    %make_install
