name       : iptables
version    : 1.6.0
release    : 5
source     :
    - http://www.netfilter.org/projects/iptables/files/iptables-1.6.0.tar.bz2 : 4bb72a0a0b18b5a9e79e87631ddc4084528e5df236bc7624472dcaa8480f1c60
license    :
    - LGPL-3.0
summary    : Netfilter firewall
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
component  : network.base
patterns   :
    - 32bit : /lib32
description: |
    Netfilter firewall
setup      : |
    rlibdir="/lib64"
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        rlibdir="/lib32"
    fi
    %configure  --exec-prefix= \
                --prefix=/usr \
                --bindir=/usr/bin                      \
                --with-xtlibdir=$rlibdir/xtables        \
                --enable-libipq                        \
                --enable-devel \
                --disable-nftables
build      : |
    %make
install    : |
    %make_install
