name       : iptables
version    : 1.8.7
release    : 10
source     :
    - https://www.netfilter.org/pub/iptables/iptables-1.8.7.tar.bz2 : c109c96bb04998cd44156622d36f8e04b140701ec60531a10668cfdff5e8d8f0
license    : LGPL-3.0-or-later
component  : network.base
summary    : Netfilter firewall
description: |
    Netfilter firewall
emul32     : yes
patterns   :
    - 32bit : /lib32
setup      : |
    %configure  --exec-prefix= \
                --bindir=/usr/bin \
                --with-xtlibdir=/lib%LIBSUFFIX%/xtables \
                --enable-libipq \
                --enable-devel \
                --disable-nftables
build      : |
    %make
install    : |
    %make_install
