name       : iptables
version    : 1.6.2
release    : 7
source     :
    - https://www.netfilter.org/projects/iptables/files/iptables-1.6.2.tar.bz2 : 55d02dfa46263343a401f297d44190f2a3e5113c8933946f094ed40237053733
license    : LGPL-3.0
component  : network.base
summary    : Netfilter firewall
description: |
    Netfilter firewall
emul32     : yes
patterns   :
    - 32bit : /lib32
setup      : |
    %configure  --exec-prefix= \
                --bindir=/usr/bin \
                --with-xtlibdir=/lib%LIBSUFFIX%/xtables \
                --enable-libipq \
                --enable-devel \
                --disable-nftables
build      : |
    %make
install    : |
    %make_install
