name       : iptables
version    : 0.9.8.0
release    : 4
source     :
    - http://www.netfilter.org/projects/iptables/files/iptables-1.4.18.tar.bz2 : 14a99fb8b0ca22027a9ac6eb72fa32c834ceb3073820e0ba79bf251c6a7bcf3c
license    :
    - LGPL-3.0
summary    : Netfilter firewall
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
patterns   :
    - 32bit: /lib32
description: |
    Netfilter firewall
setup      : |
    rlibdir="/lib"
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        rlibdir="/lib32"
    fi
    %configure  --exec-prefix= \
                --prefix=/usr \
                --bindir=/usr/bin                      \
                --with-xtlibdir=$rlibdir/xtables        \
                --enable-libipq                        \
                --enable-devel
build      : |
    %make
install    : |
    %make_install
